#Parameters for the robot
#Logging
robot_id: 0
trial_scenario: test_run

#Experiment Parameters
time_to_end: 30     # time in minutes   
robot_role: patroller #"patroller", "searcher"
num_robots: 4

#Patrol
start_node: 0
patrol_route: signal_mapping_test.csv 
patrol_method: test # "SEBS", "CGG" 

#Search
search_method: PSO # "PSO", "ECOLI", "HYBRID"
