#Parameters for the robot
#Logging
robot_id: 0
trial_scenario: test_run

#Experiment Parameters
time_to_end: 30     # time in minutes   
robot_role: patroller #"patroller", "searcher"
num_robots: 2

#Patrol
start_node: 0
patrol_route: sebstest.csv
patrol_adjacency: sebstest_unit_adj.csv  # Unit adjacency matrix, each row represents a node and the values within are the connected nodes, i.e. row 0 = 1,2
patrol_method: SEBS # "SEBS", "CGG" 

#Search
search_method: PSO # "PSO", "ECOLI", "HYBRID"
